---
title: "Mental Health Act"
author: "Andy Hood, Anya Ferguson, Andre Bilbrough, Heather Humphreys"
format:
  html:
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fig-format: svg
    mainfont: arial
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 4
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 0px
      gutter-width: 1.5rem
editor: visual
execute:
  echo: false
  message: false
  warning: false
  cache: false
lang: en-GB
date: last-modified
date-format: "YYYY-MM-DD"
title-block-banner: "#f9bf07"
title-block-banner-color: "#333739"
css: styles.css
---

```{r setup}
library(targets)
library(tidyverse)
library(scales)

source("R/quarto_formatting.R")
```

## Introduction

## Data and methods

## Summary

## Detailed analysis

### Re-detentions

```{r}
redet <- tar_read(cyp_redetentions)
```


::: panel-tabset
##### Overview

::: panel-tabset
###### Chart

```{r}
#| label: fig-redetentions-line
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions. All of England.
tar_read(cyp_avg_redetentions_rate_plot)
```

###### Table

```{r }
tar_read(cyp_avg_redetentions_rate) |>
  get_standard_table_for_breakdowns()
```
:::

##### Gender variation

::: panel-tabset
###### Chart

```{r redetentions_gender_plot}
#| label: fig-redetentions-gender
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions by gender.
tar_read(gender_plot)$cyp_redetentions
```

###### Table

```{r redetentions_gender_table}
tar_read(gender_breakdowns)$cyp_redetentions |>
  dplyr::rename(redetentions = attends) |>
  get_standard_table_for_breakdowns("gender")
```
:::

##### Age-group variation

::: panel-tabset
###### Chart

```{r redetentions_age_plot}
#| label: fig-redetentions-age
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions by age group.
tar_read(cyp_age_plot)$cyp_redetentions
```

###### Table

```{r redetentions_age_table}
tar_read(cyp_age_breakdowns)$cyp_redetentions |>
  dplyr::rename(redetentions = attends) |>
  get_standard_table_for_breakdowns("age_group")
```
:::

##### Ethnic group variation

::: panel-tabset
###### Chart

```{r redetentions_ethnic_plot}
#| label: fig-redetentions-ethnic
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions by ethnic category.
tar_read(ethnic_plot)$cyp_redetentions
```

###### Table

```{r redetentions_ethnic_table}
tar_read(ethnic_breakdowns)$cyp_redetentions |>
  dplyr::rename(redetentions = attends) |>
  get_standard_table_for_breakdowns("ethnic_category")
```
:::

##### Socioeconomic variation

::: panel-tabset
###### Chart1

```{r redetentions_imd_plot}
#| label: fig-redetentions-imd
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions by Index of Multiple Deprivation decile.
tar_read(imd_plot)$cyp_redetentions
```

###### Chart2

```{r redetentions_imd_plot2}
#| label: fig-redetentions-imd2
#| fig-cap: Rates per 100,000 population of the number of MHA redetentions by Index of Multiple Deprivation decile and year.
tar_read(cyp_redetentions_imd)
```

###### Table

```{r redetentions_imd_table}
tar_read(imd_breakdowns)$cyp_redetentions |>
  dplyr::rename(redetentions = attends) |>
  get_standard_table_for_breakdowns("imd_decile")
```
:::


### Travel distance
