---
title: "Mental Health attendances in urgent and emergency care settings"
author: "Andy Hood"
format: html
editor: visual
---

## Introduction

The care quality commission (CQC) are looking to supplement their State of Care (SOC) report with relevant additional data and analysis. The latest state of care report can be found here <https://www.cqc.org.uk/publications/major-report/state-care/2022-2023>.

One of the key areas of interest is around perceived 'system failure' as measured by (inappropriate/avoidable?) attendance to urgent and emergency care settings for people with mental health problems.

## Data and methods

We summarised routine data from the Emergency Care Dataset (ECDS), NHS 111 dataset and the Mental Health Services Dataset (MHSDS) via NCDR <https://www.ardengemcsu.nhs.uk/services/business-intelligence/ncdr/> according to specific population sub-groups and activity break-downs at Integrated Care Board (ICB) level. The period covers the 5 financial years from 1st April 2019 to 31st March 2024.

Patients were linked using pseudonymised ID from ECDS and NHS111 to the MHSDS to establish whether they were known to specialist mental health services (referred and/or treated) or not.

The presence of a presenting mental health problem in **A&E data** was determined by all descendant SNOMED codes (n=1580) for 'Mental Health Disorders' in either the Chief Complaint field *OR* the 1st Diagnosis field. The presence of mental health in **NHS 111 data** were established using a bespoke reference set for the symptom group comprising the specific mental health groups *AND* additional mentions of anxiety, depression, stress, suicidal thoughts or mental health in other symptom groups.

## Summary

Blah blah blah

## Accident and Emergency attendance

These attendances are those specified within the ECDS as 'Type 1' emergency department attendances and typically should be for those patients with life-threatening symptoms requiring immediate triage and treatment.

The average A&E attendance in England costs £280 with those conveyed by ambulance costing an additional £390 <https://www.england.nhs.uk/costing-in-the-nhs/national-cost-collection/>.

### Key metrics

### Detailed breakdowns


## Walk-in and Urgent Care attendance

These attendances are those specified within the ECDS as 'Type 3' urgent treatment centre and 'Type 4' walk-in centre attendances should be typically self-conveyed patients requiring urgent assessment and treatment to prevent deterioration.

The average urgent care attendance in England costs £107 <https://www.england.nhs.uk/costing-in-the-nhs/national-cost-collection/>.

### Key metrics

### Detailed breakdowns


## NHS 111 calls

Callers to the NHS 111 service would be typically those unable to reach primary care services or to find out information and the appropriate treatment setting for a non-urgent health complaint.

The average cost of a call to NHS 111 is around £12 with those requiring clinical call-back an extra £15 <https://www.ncbi.nlm.nih.gov/books/NBK575169/>.

### Key metrics

### Detailed breakdowns
